from .base import Architecture
from .cifarnet import CifarNet
from .cnn import CNN
from .lstm import LSTM
from .mamba import Mamba
from .mlp import MLP
from .resnet import Resnet
from .vit import VIT
from .transformer import Transformer
